version: '3.2'

services:
  nginx:
    restart: always
    image: inshopgroup/docker-inshop-crm-client-nginx-prod
    environment:
      VIRTUAL_HOST: clientdemo.yap.life
      LETSENCRYPT_HOST: clientdemo.yap.life
      LETSENCRYPT_EMAIL: info@inshop.com.ua
    volumes:
      - .:/var/www
    networks:
      - webproxy
    env_file:
      - ./.env

networks:
  webproxy:
    external:
      name: webproxy
