version: '3.2'

services:
  nginx:
    restart: always
    image: registry.inshop.com.ua/amertalk/server/docker-admin-nginx-prod
    environment:
      VIRTUAL_HOST: clientdemo.yap.life
      LETSENCRYPT_HOST: clientdemo.yap.life
      LETSENCRYPT_EMAIL: info@inshop.com.ua
    volumes:
      - .:/var/www
    networks:
      - webproxy
    env_file:
      - ./.env

networks:
  webproxy:
    external:
      name: webproxy
